# ==============================================================================
# Global Variables (Cleartext)
# ==============================================================================

# Project Name
project_name: "adsb-research-grid"

# Timezone
timezone: "Europe/Helsinki"

# ZeroTier Network ID
zerotier_network_id: "45b6e887e22d8422"

# ADS-B Receiver Settings
adsb_gain: autogain
