
# --- Identity & Location ---
hostname: "sensor-north"
timezone: "Europe/Helsinki"

# Location (From your Balena Config)
lat: 60.319555
lon: 24.830816
alt: 105

# --- Feeder Keys (Migrated from Balena) ---
# FlightAware (UUID)
piaware_feeder_id: "76d505ac-ed72-42fe-9e08-dd9ef4872c14"

# FlightRadar24 (Key)
fr24_key: "ed427e9dfc741c4b"

# PlaneFinder (Sharecode)
pf_sharecode: "6920855e1759b"

# RadarBox (Hardware Key)
rb_key: "283003ec5b08e18889e39335102e214a"

# OpenSky Network
opensky_username: "rwiren2"
opensky_serial: "2886838874"

# --- Hardware Config ---
# High-Accuracy RTK/NTRIP Credentials (Saved for Stratum-1 Role later)
ntrip_host: "opencaster.nls.fi"
ntrip_mount: "VRS-FKP"
ntrip_user: "rwiren"
ntrip_pass: "Riku3404"
