---
# ==============================================================================
# HANDLERS: GNSS Receiver
# FILE: infra/ansible/roles/gnss-receiver/handlers/main.yml
# VERSION: 0.4.4
# ==============================================================================

- name: Restart GPSD
  service:
    name: gpsd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Data Hub
  service:
    name: gnss-socat-hub
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart NTRIP Client
  service:
    name: gnss-ntrip-client
    state: restarted
    enabled: yes
    daemon_reload: yes
