---
- name: restart adsb-recorder
  systemd:
    name: adsb-recorder
    state: restarted
    daemon_reload: yes

- name: restart gnss-recorder
  systemd:
    name: gnss-recorder
    state: restarted
    daemon_reload: yes
