---
# ==============================================================================
# Global Variables
# ==============================================================================

# Project Name
project_name: "adsb-research-grid"

# Timezone
timezone: "Europe/Helsinki"

# ZeroTier Network ID (Verified from Screenshot)
zerotier_network_id: "45b6e887e22d8422"

# ADS-B Receiver Settings
# 'autogain' is best for general use. Use specific dB (e.g. 49.6) if needed.
adsb_gain: autogain
